name: Deploy Strapi to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Ensuring target directory exists..."
            mkdir -p /home/ubuntu/strapidocker
            
            echo "Navigating to target directory..."
            cd /home/ubuntu/strapidocker || { echo "Directory not found"; exit 1; }
            
            echo "Checking npm installation..."
            if ! command -v npm &> /dev/null; then
              echo "Installing Node.js and npm..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            else
              echo "npm is already installed"
            fi
            
            echo "Installing project dependencies..."
            npm install || { echo "npm install failed"; exit 1; }
            
            echo "Starting Strapi..."
            npm run develop || { echo "Strapi failed to start"; exit 1; }
